# Generated by Django 3.0 on 2021-02-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='Add a description here', max_length=2000),
            preserve_default=False,
        ),
    ]
